name: CI/CD Client

on:
  push:
    paths:
      - 'client/**'
    branches: [deploiement]

env:
  AWS_REGION: eu-west-1
  ECR_REGISTRY: 61070557184.dkr.ecr.eu-west-1.amazonaws.com
  IMAGE_NAME: client

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        working-directory: client
        run: mvn clean install -DskipTests

      - name: Run tests
        working-directory: client
        run: mvn test

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: client
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: client
          SONAR_ORG: ton_org_sonarcloud

      - name: Authenticate with AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build and push Docker image
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_NAME:latest client/
          docker push $ECR_REGISTRY/$IMAGE_NAME:latest
